#!/bin/sh

datetime() {
	time="$(date "+ %H:%M:%S %Z | %a %d %b %Y ")"

}

volume() {
	vol="Vol : $(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%" 
}

while true
do
	volume
	datetime
	xsetroot -name "| $vol |$time";
	sleep 1s;
done
