#!/bin/sh

refresh_data() {
	time="$(date "+ %H:%M %Z | %a %d %b %Y ")"
	vol="Vol : $(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')%"
	bat="Bt: $(cat /sys/class/power_supply/BAT0/capacity)%"
	bright="B: $(cat /sys/class/backlight/intel_backlight/brightness)%"
}

while true
do
	refresh_data
	xsetroot -name "| $bat | $bright | $vol |$time";
	sleep 1m;
done
