#!/bin/bash

# start dwm

xrdb -merge $HOME/.Xresources
xrdb -merge ~/.Xdefaults

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg, pkcs11, secrets, ssh)

export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

export QT_STYLE_OVERRIDE=gtk

~/.fehbg &
dwmbar &
compton --backend glx --vsync opengl-swc --blur-background-fixed &
exec dwm
